services:
  csbsr:
    build:
      context: .
    image: python3.14.2:trixie-slim-uv
    container_name: csbsr
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/csbsr
      - /tmp/.X11-unix:/tmp/.X11-unix

  csbsr-gpu:
    extends:
      service: csbsr
    container_name: csbsr-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
